name: Auto Submit

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-24.04

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 📦 Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: 🌐 Install Chromium
        run: |
          sudo apt update
          sudo apt install -y chromium-browser

      - name: ▶ Run Bot
        env:
          PANEL_USER: ${{ secrets.PANEL_USER }}
          PANEL_PASS: ${{ secrets.PANEL_PASS }}
        run: python auto_submit.py

      - name: 📸 Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: "*.png"
